part1: part1.cpp
	@g++ part1.cpp
	@time ./a.out input.ppm output_part1.ppm
	
part2_1a: part2_1a.cpp
	@g++ part2_1a.cpp -lpthread
	@time ./a.out input.ppm output_part2_1a.ppm
	
part2_1b: part2_1b.cpp
	@g++ part2_1b.cpp -lpthread
	@time ./a.out input.ppm output_part2_1b.ppm
	
part2_2: part2_2.cpp
	@g++ part2_2.cpp -lpthread
	@time ./a.out input.ppm output_part2_2.ppm
	
part2_3: part2_3.cpp
	@g++ part2_3.cpp -lpthread
	@time ./a.out input.ppm output_part2_3.ppm
